### ISSUE TITLE
Unable to Build / Any Further Exploration?

### ISSUE THREAD

**Issue by gylippus** [ionic-team/cordova-plugin-localstorage-backup#1]
Hey @jbavari thanks for looking into this. I was revisiting as I just discovered that Crosswalk is the only way for us to get past an HTML5 video issue on some older Samsung devices that are stuck with a buggy version of the Chromium default browser with no hopes of that being updates. 

I was trying to test this plugin and the method that you mentioned in your notes, makeWebView() is blocking me from even being able to to ionic run android as it "cannot find symbol". The comments for makeWebView() in CordovaActivity.java mention it is intended to be overideable by subclasses of CordovaIntent

```
    /**
     * Construct the default web view object.
     *
     * This is intended to be overridable by subclasses of CordovaIntent which
     * require a more specialized web view.
     */
    protected CordovaWebView makeWebView() {
        return new CordovaWebView(CordovaActivity.this);
    }
```

Does this lead to any other thoughts here to make accessing the older default browser?

If Max a crew have you too tied up, do you know anyone else who may be interested in contracting to progress this a bit further?

Thanks.

**Comment by jeroenmaas** [comment]
Hey gylippus,

We ran in the same issue. We decided to use the default webview in combination with runOnUiThread. This might also work for you. You can find at https://github.com/munisense/cordova-plugin-local-storage-retrieval and it works just like a normal cordova plugin. 

Regards,

Jeroen

**Comment by Ionitron** [comment]
Greetings @gylippus!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
